# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

#[key-mapping.key-notation-to-key-code]
#mod = 'alt-cmd'
#mod2 = 'alt-cmd-ctrl'

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''

# i3 wraps focus by default
alt-cmd-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-cmd-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-cmd-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-cmd-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-cmd-ctrl-h = 'move left'
alt-cmd-ctrl-j = 'move down'
alt-cmd-ctrl-k = 'move up'
alt-cmd-ctrl-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-cmd-backslash = 'split horizontal'
alt-cmd-minus = 'split vertical'

alt-cmd-f = 'fullscreen'
alt-cmd-ctrl-f = 'fullscreen --no-outer-gaps'

alt-cmd-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-cmd-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-cmd-ctrl-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-cmd-1 = 'workspace 1'
alt-cmd-2 = 'workspace 2'
alt-cmd-3 = 'workspace 3'
alt-cmd-4 = 'workspace 4'
alt-cmd-5 = 'workspace 5'
alt-cmd-6 = 'workspace 6'
alt-cmd-7 = 'workspace 7'
alt-cmd-8 = 'workspace 8'
alt-cmd-9 = 'workspace 9'
alt-cmd-0 = 'workspace 10'

alt-cmd-ctrl-1 = 'move-node-to-workspace 1'
alt-cmd-ctrl-2 = 'move-node-to-workspace 2'
alt-cmd-ctrl-3 = 'move-node-to-workspace 3'
alt-cmd-ctrl-4 = 'move-node-to-workspace 4'
alt-cmd-ctrl-5 = 'move-node-to-workspace 5'
alt-cmd-ctrl-6 = 'move-node-to-workspace 6'
alt-cmd-ctrl-7 = 'move-node-to-workspace 7'
alt-cmd-ctrl-8 = 'move-node-to-workspace 8'
alt-cmd-ctrl-9 = 'move-node-to-workspace 9'
alt-cmd-ctrl-0 = 'move-node-to-workspace 10'

alt-cmd-ctrl-c = 'reload-config'

# alt-cmd-q = 'close'
alt-cmd-ctrl-q = 'close --quit-if-last-window'

alt-cmd-r = 'mode resize'

# alt-cmd-ctrl-o = 'exec-and-forget open -n /Applications/Sol.app/Contents/MacOS/sol'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
