require 'plugins.colorizer'
require 'plugins.discord'
require 'plugins.editor'
require 'plugins.hydra'
require 'plugins.lsp'
require 'plugins.multicursor'
require 'plugins.precognition'
require 'plugins.theme'

require 'config.extra.after'
